name: Build

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Target Domain'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Build
      run: |
        TARGET_URL=${{ github.event.inputs.domain }} GOOS=linux GOARCH=amd64 go build -o main main.go
    - name: Zip the Build
      run: zip main.zip main scf_bootstrap
    - name: Upload ZIP Artifact
      uses: actions/upload-artifact@v2
      with:
        name: main.zip
        path: main.zip
